function[ l_c_mpo_left, l_c_mpo_rigth, l_O]= build_hamiltonian_xx_yy(d_exp,N)
       for k_exp = 1:length(d_exp.beta)  
[l_c_mpo_left{k_exp}, l_c_mpo_rigth{k_exp}, l_O{k_exp}] = build_mpo(...
            diag([1,d_exp.beta(k_exp),d_exp.beta(k_exp),1]),...
            [0,-d_exp.alpha(k_exp),0,0;...
             0,0,0,1;...
             0,0,0,0;...
             0,0,0,0],...
            [0,0,-d_exp.alpha(k_exp),0;...
             0,0,0,0;...
             0,0,0,1;...
              0,0,0,0],...
              [0,0,0,0;...
             0,0,0,0;...
             0,0,0,0;...
              0,0,0,0],...  
           1,...
            N);
       end
end
%        for k_exp = 2:length(d_exp.beta)
%              [l_c_mpo_left{k_exp}, l_c_mpo_rigth{k_exp}, l_O{k_exp}] = build_mpo(...
%              diag([1,d_exp.beta(k_exp),d_exp.beta(k_exp),d_exp.beta(k_exp),1]),...
%             [0,sin(theta)*d_exp.alpha(k_exp),0,0,0;...
%              0,0,0,0,1;...
%              0,0,0,0,0;...
%              0,0,0,0,0;...
%              0,0,0,0,0],...
%             [0,0,sin(theta)*d_exp.alpha(k_exp),0,0;...
%              0,0,0,0,0;...
%              0,0,0,0,1;...
%              0,0,0,0,0;...
%              0,0,0,0,0],...,...
%             [0,0,0,cos(theta)*d_exp.alpha(k_exp),0;...
%              0,0,0,0,0;...
%              0,0,0,0,0;...
%              0,0,0,0,1;...
%              0,0,0,0,0],...
%             1,...
%             N);
%         end

